site_name: 'Wild'
site_url: 'https://daio-io.github.io/wild/'
edit_uri: 'tree/main/docs/'
remote_branch: gh-pages

nav:
  - 'Overview': index.md
  - 'Foundations': foundations.md
  - 'Content Color': content-color.md
  - 'Style': style.md
  - 'Container': container.md
  - 'Button': button.md
  - 'Modifier': modifier.md
  - 'Api Reference': reference/

theme:
  name: material
  language: 'en'
  icon:
    logo: material/nature
  palette:
    scheme: slate
    primary: black
    accent: deep orange
  features:
    - navigation.instant
    -
markdown_extensions:
  - admonition