site_name: 'Wild'
site_url: 'https://daio-io.github.io/wild/'
edit_uri: 'tree/main/docs/'
remote_branch: gh-pages

# Repository
repo_name: daio-io/wild
repo_url: https://github.com/daio-io/wild

copyright: Copyright &copy; 2024 Dai Williams

nav:
  - 'Overview': index.md
  - 'Foundations': foundations.md
  - 'Tv': tv.md
  - 'Content Color': content-color.md
  - 'Style': style.md
  - 'Container': container.md
  - 'Button': button.md
  - 'Modifier': modifier.md
  - 'Api Reference': reference/

theme:
  name: material
  language: 'en'
  logo: wild-icon.svg
  favicon: wild-favicon.svg
  icon:
    logo: material/nature
  palette:
    scheme: slate
    primary: black
    accent: deep orange
  features:
    - navigation.instant
    -
markdown_extensions:
  - admonition