site_name: Wild
site_url: https://daio-io.github.io/wild/

nav:
  - 'Overview': index.md
  - 'Foundations': foundations.md
  - 'Container': container.md
  - 'Button': button.md
  - 'Modifier': modifier.md

theme:
  name: material
  language: 'en'
  icon:
    logo: material/nature
  palette:
    scheme: slate
    primary: black
    accent: deep orange
  features:
    - navigation.instant