name: Deploy Docs

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install MkDocs
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs-material

      - name: Build the site
        run: mkdocs build

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Kdoc
        run: ./gradlew dokkaHtmlMultiModule

      - name: Copy Kdoc Site
        run: mkdir -p ./site/reference && cp -r ./build/dokka/htmlMultiModule/* ./site/reference

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4